// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthData, GetRunsByIdData, GetRunsByIdErrors, GetRunsByIdEventsData, GetRunsByIdEventsErrors, GetRunsByIdEventsResponses, GetRunsByIdMessagesData, GetRunsByIdMessagesErrors, GetRunsByIdMessagesResponses, GetRunsByIdResponses, GetRunsByIdStreamData, GetRunsByIdToolExecutionsData, GetRunsByIdToolExecutionsErrors, GetRunsByIdToolExecutionsResponses, GetWorkspacesByIdData, GetWorkspacesByIdErrors, GetWorkspacesByIdResponses, GetWorkspacesData, GetWorkspacesResponses, PostWorkspacesByIdRunsData, PostWorkspacesByIdRunsErrors, PostWorkspacesByIdRunsResponses, PostWorkspacesData, PostWorkspacesErrors, PostWorkspacesResponses } from './types.gen';
import { zGetHealthData, zGetRunsByIdData, zGetRunsByIdEventsData, zGetRunsByIdMessagesData, zGetRunsByIdStreamData, zGetRunsByIdToolExecutionsData, zGetWorkspacesByIdData, zGetWorkspacesData, zPostWorkspacesByIdRunsData, zPostWorkspacesData } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetHealthData.parseAsync(data),
    url: '/health',
    ...options
});

export const getWorkspaces = <ThrowOnError extends boolean = false>(options?: Options<GetWorkspacesData, ThrowOnError>) => (options?.client ?? client).get<GetWorkspacesResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetWorkspacesData.parseAsync(data),
    url: '/workspaces/',
    ...options
});

export const postWorkspaces = <ThrowOnError extends boolean = false>(options: Options<PostWorkspacesData, ThrowOnError>) => (options.client ?? client).post<PostWorkspacesResponses, PostWorkspacesErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostWorkspacesData.parseAsync(data),
    url: '/workspaces/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getWorkspacesById = <ThrowOnError extends boolean = false>(options: Options<GetWorkspacesByIdData, ThrowOnError>) => (options.client ?? client).get<GetWorkspacesByIdResponses, GetWorkspacesByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetWorkspacesByIdData.parseAsync(data),
    url: '/workspaces/{id}',
    ...options
});

export const postWorkspacesByIdRuns = <ThrowOnError extends boolean = false>(options: Options<PostWorkspacesByIdRunsData, ThrowOnError>) => (options.client ?? client).post<PostWorkspacesByIdRunsResponses, PostWorkspacesByIdRunsErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostWorkspacesByIdRunsData.parseAsync(data),
    url: '/workspaces/{id}/runs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getRunsById = <ThrowOnError extends boolean = false>(options: Options<GetRunsByIdData, ThrowOnError>) => (options.client ?? client).get<GetRunsByIdResponses, GetRunsByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetRunsByIdData.parseAsync(data),
    url: '/runs/{id}',
    ...options
});

export const getRunsByIdEvents = <ThrowOnError extends boolean = false>(options: Options<GetRunsByIdEventsData, ThrowOnError>) => (options.client ?? client).get<GetRunsByIdEventsResponses, GetRunsByIdEventsErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetRunsByIdEventsData.parseAsync(data),
    url: '/runs/{id}/events',
    ...options
});

export const getRunsByIdToolExecutions = <ThrowOnError extends boolean = false>(options: Options<GetRunsByIdToolExecutionsData, ThrowOnError>) => (options.client ?? client).get<GetRunsByIdToolExecutionsResponses, GetRunsByIdToolExecutionsErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetRunsByIdToolExecutionsData.parseAsync(data),
    url: '/runs/{id}/tool-executions',
    ...options
});

export const getRunsByIdMessages = <ThrowOnError extends boolean = false>(options: Options<GetRunsByIdMessagesData, ThrowOnError>) => (options.client ?? client).get<GetRunsByIdMessagesResponses, GetRunsByIdMessagesErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetRunsByIdMessagesData.parseAsync(data),
    url: '/runs/{id}/messages',
    ...options
});

export const getRunsByIdStream = <ThrowOnError extends boolean = false>(options: Options<GetRunsByIdStreamData, ThrowOnError>) => (options.client ?? client).get<unknown, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetRunsByIdStreamData.parseAsync(data),
    url: '/runs/{id}/stream',
    ...options
});
