// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAgentProvidersByIdData, DeleteAgentProvidersByIdErrors, DeleteAgentProvidersByIdResponses, DeleteSystemConfigsByKeyData, DeleteSystemConfigsByKeyErrors, DeleteSystemConfigsByKeyResponses, GetAgentProvidersData, GetAgentProvidersErrors, GetAgentProvidersResponses, GetHealthData, GetRunsByIdData, GetRunsByIdErrors, GetRunsByIdEventsData, GetRunsByIdEventsErrors, GetRunsByIdEventsResponses, GetRunsByIdResponses, GetRunsByIdStreamData, GetRunsByIdStreamErrors, GetRunsByIdStreamResponses, GetRunsByIdToolExecutionsData, GetRunsByIdToolExecutionsErrors, GetRunsByIdToolExecutionsResponses, GetSystemConfigsByKeyData, GetSystemConfigsByKeyErrors, GetSystemConfigsByKeyResponses, GetSystemConfigsData, GetSystemConfigsErrors, GetSystemConfigsResponses, GetWorkspacesByIdData, GetWorkspacesByIdErrors, GetWorkspacesByIdResponses, GetWorkspacesData, GetWorkspacesErrors, GetWorkspacesResponses, GetWorkspacesSearchData, GetWorkspacesSearchErrors, GetWorkspacesSearchResponses, PostAgentProvidersByIdActivateData, PostAgentProvidersByIdActivateErrors, PostAgentProvidersByIdActivateResponses, PostAgentProvidersData, PostAgentProvidersErrors, PostAgentProvidersResponses, PostRunsByIdCancelData, PostRunsByIdCancelErrors, PostRunsByIdCancelResponses, PostRunsByIdEventsData, PostRunsByIdEventsErrors, PostRunsByIdEventsResponses, PostWorkspacesByIdArchiveData, PostWorkspacesByIdArchiveErrors, PostWorkspacesByIdArchiveResponses, PostWorkspacesByIdCompactData, PostWorkspacesByIdCompactErrors, PostWorkspacesByIdCompactResponses, PostWorkspacesByIdRunsData, PostWorkspacesByIdRunsErrors, PostWorkspacesByIdRunsResponses, PostWorkspacesData, PostWorkspacesErrors, PostWorkspacesResponses, PutAgentProvidersByIdData, PutAgentProvidersByIdErrors, PutAgentProvidersByIdResponses, PutSystemConfigsByKeyData, PutSystemConfigsByKeyErrors, PutSystemConfigsByKeyResponses } from './types.gen';
import { zDeleteAgentProvidersByIdData, zDeleteSystemConfigsByKeyData, zGetAgentProvidersData, zGetHealthData, zGetRunsByIdData, zGetRunsByIdEventsData, zGetRunsByIdStreamData, zGetRunsByIdToolExecutionsData, zGetSystemConfigsByKeyData, zGetSystemConfigsData, zGetWorkspacesByIdData, zGetWorkspacesData, zGetWorkspacesSearchData, zPostAgentProvidersByIdActivateData, zPostAgentProvidersData, zPostRunsByIdCancelData, zPostRunsByIdEventsData, zPostWorkspacesByIdArchiveData, zPostWorkspacesByIdCompactData, zPostWorkspacesByIdRunsData, zPostWorkspacesData, zPutAgentProvidersByIdData, zPutSystemConfigsByKeyData } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getSystemConfigs = <ThrowOnError extends boolean = false>(options?: Options<GetSystemConfigsData, ThrowOnError>) => (options?.client ?? client).get<GetSystemConfigsResponses, GetSystemConfigsErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetSystemConfigsData.parseAsync(data),
    url: '/system-configs/',
    ...options
});

export const deleteSystemConfigsByKey = <ThrowOnError extends boolean = false>(options: Options<DeleteSystemConfigsByKeyData, ThrowOnError>) => (options.client ?? client).delete<DeleteSystemConfigsByKeyResponses, DeleteSystemConfigsByKeyErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteSystemConfigsByKeyData.parseAsync(data),
    url: '/system-configs/{key}',
    ...options
});

export const getSystemConfigsByKey = <ThrowOnError extends boolean = false>(options: Options<GetSystemConfigsByKeyData, ThrowOnError>) => (options.client ?? client).get<GetSystemConfigsByKeyResponses, GetSystemConfigsByKeyErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetSystemConfigsByKeyData.parseAsync(data),
    url: '/system-configs/{key}',
    ...options
});

export const putSystemConfigsByKey = <ThrowOnError extends boolean = false>(options: Options<PutSystemConfigsByKeyData, ThrowOnError>) => (options.client ?? client).put<PutSystemConfigsByKeyResponses, PutSystemConfigsByKeyErrors, ThrowOnError>({
    requestValidator: async (data) => await zPutSystemConfigsByKeyData.parseAsync(data),
    url: '/system-configs/{key}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAgentProviders = <ThrowOnError extends boolean = false>(options?: Options<GetAgentProvidersData, ThrowOnError>) => (options?.client ?? client).get<GetAgentProvidersResponses, GetAgentProvidersErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetAgentProvidersData.parseAsync(data),
    url: '/agent/providers/',
    ...options
});

export const postAgentProviders = <ThrowOnError extends boolean = false>(options: Options<PostAgentProvidersData, ThrowOnError>) => (options.client ?? client).post<PostAgentProvidersResponses, PostAgentProvidersErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostAgentProvidersData.parseAsync(data),
    url: '/agent/providers/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteAgentProvidersById = <ThrowOnError extends boolean = false>(options: Options<DeleteAgentProvidersByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteAgentProvidersByIdResponses, DeleteAgentProvidersByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteAgentProvidersByIdData.parseAsync(data),
    url: '/agent/providers/{id}',
    ...options
});

export const putAgentProvidersById = <ThrowOnError extends boolean = false>(options: Options<PutAgentProvidersByIdData, ThrowOnError>) => (options.client ?? client).put<PutAgentProvidersByIdResponses, PutAgentProvidersByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await zPutAgentProvidersByIdData.parseAsync(data),
    url: '/agent/providers/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAgentProvidersByIdActivate = <ThrowOnError extends boolean = false>(options: Options<PostAgentProvidersByIdActivateData, ThrowOnError>) => (options.client ?? client).post<PostAgentProvidersByIdActivateResponses, PostAgentProvidersByIdActivateErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostAgentProvidersByIdActivateData.parseAsync(data),
    url: '/agent/providers/{id}/activate',
    ...options
});

export const getWorkspaces = <ThrowOnError extends boolean = false>(options?: Options<GetWorkspacesData, ThrowOnError>) => (options?.client ?? client).get<GetWorkspacesResponses, GetWorkspacesErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetWorkspacesData.parseAsync(data),
    url: '/workspaces/',
    ...options
});

export const postWorkspaces = <ThrowOnError extends boolean = false>(options: Options<PostWorkspacesData, ThrowOnError>) => (options.client ?? client).post<PostWorkspacesResponses, PostWorkspacesErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostWorkspacesData.parseAsync(data),
    url: '/workspaces/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getWorkspacesSearch = <ThrowOnError extends boolean = false>(options: Options<GetWorkspacesSearchData, ThrowOnError>) => (options.client ?? client).get<GetWorkspacesSearchResponses, GetWorkspacesSearchErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetWorkspacesSearchData.parseAsync(data),
    url: '/workspaces/search',
    ...options
});

export const getWorkspacesById = <ThrowOnError extends boolean = false>(options: Options<GetWorkspacesByIdData, ThrowOnError>) => (options.client ?? client).get<GetWorkspacesByIdResponses, GetWorkspacesByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetWorkspacesByIdData.parseAsync(data),
    url: '/workspaces/{id}',
    ...options
});

export const postWorkspacesByIdArchive = <ThrowOnError extends boolean = false>(options: Options<PostWorkspacesByIdArchiveData, ThrowOnError>) => (options.client ?? client).post<PostWorkspacesByIdArchiveResponses, PostWorkspacesByIdArchiveErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostWorkspacesByIdArchiveData.parseAsync(data),
    url: '/workspaces/{id}/archive',
    ...options
});

export const postWorkspacesByIdRuns = <ThrowOnError extends boolean = false>(options: Options<PostWorkspacesByIdRunsData, ThrowOnError>) => (options.client ?? client).post<PostWorkspacesByIdRunsResponses, PostWorkspacesByIdRunsErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostWorkspacesByIdRunsData.parseAsync(data),
    url: '/workspaces/{id}/runs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postWorkspacesByIdCompact = <ThrowOnError extends boolean = false>(options: Options<PostWorkspacesByIdCompactData, ThrowOnError>) => (options.client ?? client).post<PostWorkspacesByIdCompactResponses, PostWorkspacesByIdCompactErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostWorkspacesByIdCompactData.parseAsync(data),
    url: '/workspaces/{id}/compact',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetHealthData.parseAsync(data),
    url: '/health',
    ...options
});

export const getRunsById = <ThrowOnError extends boolean = false>(options: Options<GetRunsByIdData, ThrowOnError>) => (options.client ?? client).get<GetRunsByIdResponses, GetRunsByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetRunsByIdData.parseAsync(data),
    url: '/runs/{id}',
    ...options
});

export const getRunsByIdEvents = <ThrowOnError extends boolean = false>(options: Options<GetRunsByIdEventsData, ThrowOnError>) => (options.client ?? client).get<GetRunsByIdEventsResponses, GetRunsByIdEventsErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetRunsByIdEventsData.parseAsync(data),
    url: '/runs/{id}/events',
    ...options
});

export const postRunsByIdEvents = <ThrowOnError extends boolean = false>(options: Options<PostRunsByIdEventsData, ThrowOnError>) => (options.client ?? client).post<PostRunsByIdEventsResponses, PostRunsByIdEventsErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostRunsByIdEventsData.parseAsync(data),
    url: '/runs/{id}/events',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getRunsByIdToolExecutions = <ThrowOnError extends boolean = false>(options: Options<GetRunsByIdToolExecutionsData, ThrowOnError>) => (options.client ?? client).get<GetRunsByIdToolExecutionsResponses, GetRunsByIdToolExecutionsErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetRunsByIdToolExecutionsData.parseAsync(data),
    url: '/runs/{id}/tool-executions',
    ...options
});

export const postRunsByIdCancel = <ThrowOnError extends boolean = false>(options: Options<PostRunsByIdCancelData, ThrowOnError>) => (options.client ?? client).post<PostRunsByIdCancelResponses, PostRunsByIdCancelErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostRunsByIdCancelData.parseAsync(data),
    url: '/runs/{id}/cancel',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getRunsByIdStream = <ThrowOnError extends boolean = false>(options: Options<GetRunsByIdStreamData, ThrowOnError>) => (options.client ?? client).get<GetRunsByIdStreamResponses, GetRunsByIdStreamErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetRunsByIdStreamData.parseAsync(data),
    url: '/runs/{id}/stream',
    ...options
});
