// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetWorkspacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workspaces/';
};

export type GetWorkspacesErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
};

export type GetWorkspacesError = GetWorkspacesErrors[keyof GetWorkspacesErrors];

export type GetWorkspacesResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetWorkspacesResponse = GetWorkspacesResponses[keyof GetWorkspacesResponses];

export type PostWorkspacesData = {
    body: {
        name: string;
        rootPath?: string;
        telegramChatId?: string;
        telegramUserId?: string;
        forkedFromSessionId?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/workspaces/';
};

export type PostWorkspacesErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostWorkspacesError = PostWorkspacesErrors[keyof PostWorkspacesErrors];

export type PostWorkspacesResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostWorkspacesResponse = PostWorkspacesResponses[keyof PostWorkspacesResponses];

export type GetWorkspacesSearchData = {
    body?: never;
    path?: never;
    query: {
        chatId: string;
        userId?: string;
        query?: string;
    };
    url: '/workspaces/search';
};

export type GetWorkspacesSearchErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
};

export type GetWorkspacesSearchError = GetWorkspacesSearchErrors[keyof GetWorkspacesSearchErrors];

export type GetWorkspacesSearchResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetWorkspacesSearchResponse = GetWorkspacesSearchResponses[keyof GetWorkspacesSearchResponses];

export type GetWorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}';
};

export type GetWorkspacesByIdErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetWorkspacesByIdError = GetWorkspacesByIdErrors[keyof GetWorkspacesByIdErrors];

export type GetWorkspacesByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetWorkspacesByIdResponse = GetWorkspacesByIdResponses[keyof GetWorkspacesByIdResponses];

export type PostWorkspacesByIdRunsData = {
    body: {
        prompt: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}/runs';
};

export type PostWorkspacesByIdRunsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostWorkspacesByIdRunsError = PostWorkspacesByIdRunsErrors[keyof PostWorkspacesByIdRunsErrors];

export type PostWorkspacesByIdRunsResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        sessionId: string;
        prompt: string;
        status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
        summary?: string;
        error?: string;
        startedAt?: string;
        finishedAt?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostWorkspacesByIdRunsResponse = PostWorkspacesByIdRunsResponses[keyof PostWorkspacesByIdRunsResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetRunsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}';
};

export type GetRunsByIdErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdError = GetRunsByIdErrors[keyof GetRunsByIdErrors];

export type GetRunsByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        sessionId: string;
        prompt: string;
        status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
        summary?: string;
        error?: string;
        startedAt?: string;
        finishedAt?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetRunsByIdResponse = GetRunsByIdResponses[keyof GetRunsByIdResponses];

export type GetRunsByIdEventsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/events';
};

export type GetRunsByIdEventsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdEventsError = GetRunsByIdEventsErrors[keyof GetRunsByIdEventsErrors];

export type GetRunsByIdEventsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        runId: string;
        type: 'run.queued' | 'run.started' | 'run.progress' | 'run.completed' | 'run.failed' | 'run.canceled' | 'tool.executed';
        message: string;
        payload?: {
            [key: string]: unknown;
        };
        timestamp: string;
    }>;
};

export type GetRunsByIdEventsResponse = GetRunsByIdEventsResponses[keyof GetRunsByIdEventsResponses];

export type PostRunsByIdEventsData = {
    body: {
        type: 'run.queued' | 'run.started' | 'run.progress' | 'run.completed' | 'run.failed' | 'run.canceled' | 'tool.executed';
        message: string;
        payload?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/events';
};

export type PostRunsByIdEventsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostRunsByIdEventsError = PostRunsByIdEventsErrors[keyof PostRunsByIdEventsErrors];

export type PostRunsByIdEventsResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        runId: string;
        type: 'run.queued' | 'run.started' | 'run.progress' | 'run.completed' | 'run.failed' | 'run.canceled' | 'tool.executed';
        message: string;
        payload?: {
            [key: string]: unknown;
        };
        timestamp: string;
    };
};

export type PostRunsByIdEventsResponse = PostRunsByIdEventsResponses[keyof PostRunsByIdEventsResponses];

export type GetRunsByIdToolExecutionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/tool-executions';
};

export type GetRunsByIdToolExecutionsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdToolExecutionsError = GetRunsByIdToolExecutionsErrors[keyof GetRunsByIdToolExecutionsErrors];

export type GetRunsByIdToolExecutionsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        runId: string;
        tool: string;
        input: unknown;
        output: unknown;
        status: 'succeeded' | 'failed';
        error?: string;
        startedAt: string;
        endedAt?: string;
    }>;
};

export type GetRunsByIdToolExecutionsResponse = GetRunsByIdToolExecutionsResponses[keyof GetRunsByIdToolExecutionsResponses];

export type PostRunsByIdCancelData = {
    body: {
        reason?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/cancel';
};

export type PostRunsByIdCancelErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostRunsByIdCancelError = PostRunsByIdCancelErrors[keyof PostRunsByIdCancelErrors];

export type PostRunsByIdCancelResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        sessionId: string;
        prompt: string;
        status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
        summary?: string;
        error?: string;
        startedAt?: string;
        finishedAt?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostRunsByIdCancelResponse = PostRunsByIdCancelResponses[keyof PostRunsByIdCancelResponses];

export type GetRunsByIdStreamData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/stream';
};

export type GetRunsByIdStreamErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdStreamError = GetRunsByIdStreamErrors[keyof GetRunsByIdStreamErrors];

export type GetRunsByIdStreamResponses = {
    /**
     * text/event-stream
     */
    200: unknown;
};
