// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetWorkspacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workspaces/';
};

export type GetWorkspacesResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetWorkspacesResponse = GetWorkspacesResponses[keyof GetWorkspacesResponses];

export type PostWorkspacesData = {
    body: {
        name: string;
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/workspaces/';
};

export type PostWorkspacesErrors = {
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostWorkspacesError = PostWorkspacesErrors[keyof PostWorkspacesErrors];

export type PostWorkspacesResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostWorkspacesResponse = PostWorkspacesResponses[keyof PostWorkspacesResponses];

export type GetWorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}';
};

export type GetWorkspacesByIdErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetWorkspacesByIdError = GetWorkspacesByIdErrors[keyof GetWorkspacesByIdErrors];

export type GetWorkspacesByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetWorkspacesByIdResponse = GetWorkspacesByIdResponses[keyof GetWorkspacesByIdResponses];

export type PostWorkspacesByIdRunsData = {
    body: {
        prompt: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}/runs';
};

export type PostWorkspacesByIdRunsErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostWorkspacesByIdRunsError = PostWorkspacesByIdRunsErrors[keyof PostWorkspacesByIdRunsErrors];

export type PostWorkspacesByIdRunsResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        sessionId: string;
        prompt: string;
        status: 'queued' | 'running' | 'succeeded' | 'failed';
        summary?: string;
        error?: string;
        startedAt?: string;
        finishedAt?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostWorkspacesByIdRunsResponse = PostWorkspacesByIdRunsResponses[keyof PostWorkspacesByIdRunsResponses];

export type GetRunsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}';
};

export type GetRunsByIdErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdError = GetRunsByIdErrors[keyof GetRunsByIdErrors];

export type GetRunsByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        sessionId: string;
        prompt: string;
        status: 'queued' | 'running' | 'succeeded' | 'failed';
        summary?: string;
        error?: string;
        startedAt?: string;
        finishedAt?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetRunsByIdResponse = GetRunsByIdResponses[keyof GetRunsByIdResponses];

export type GetRunsByIdEventsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/events';
};

export type GetRunsByIdEventsErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdEventsError = GetRunsByIdEventsErrors[keyof GetRunsByIdEventsErrors];

export type GetRunsByIdEventsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        runId: string;
        type: 'run.queued' | 'run.started' | 'run.progress' | 'run.completed' | 'run.failed' | 'tool.executed';
        message: string;
        payload?: {
            [key: string]: unknown;
        };
        timestamp: string;
    }>;
};

export type GetRunsByIdEventsResponse = GetRunsByIdEventsResponses[keyof GetRunsByIdEventsResponses];

export type GetRunsByIdToolExecutionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/tool-executions';
};

export type GetRunsByIdToolExecutionsErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdToolExecutionsError = GetRunsByIdToolExecutionsErrors[keyof GetRunsByIdToolExecutionsErrors];

export type GetRunsByIdToolExecutionsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        runId: string;
        tool: string;
        input: unknown;
        output: unknown;
        status: 'succeeded' | 'failed';
        error?: string;
        startedAt: string;
        endedAt?: string;
    }>;
};

export type GetRunsByIdToolExecutionsResponse = GetRunsByIdToolExecutionsResponses[keyof GetRunsByIdToolExecutionsResponses];

export type GetRunsByIdMessagesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/messages';
};

export type GetRunsByIdMessagesErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdMessagesError = GetRunsByIdMessagesErrors[keyof GetRunsByIdMessagesErrors];

export type GetRunsByIdMessagesResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        sessionId: string;
        runId?: string;
        kind: 'info' | 'progress' | 'result' | 'tool' | 'error';
        content: string;
        metadata?: {
            [key: string]: unknown;
        };
        timestamp: string;
    }>;
};

export type GetRunsByIdMessagesResponse = GetRunsByIdMessagesResponses[keyof GetRunsByIdMessagesResponses];

export type GetRunsByIdStreamData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/stream';
};
