// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetSystemConfigsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/system-configs/';
};

export type GetSystemConfigsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
};

export type GetSystemConfigsError = GetSystemConfigsErrors[keyof GetSystemConfigsErrors];

export type GetSystemConfigsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        key: string;
        value: unknown;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetSystemConfigsResponse = GetSystemConfigsResponses[keyof GetSystemConfigsResponses];

export type DeleteSystemConfigsByKeyData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/system-configs/{key}';
};

export type DeleteSystemConfigsByKeyErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type DeleteSystemConfigsByKeyError = DeleteSystemConfigsByKeyErrors[keyof DeleteSystemConfigsByKeyErrors];

export type DeleteSystemConfigsByKeyResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        key: string;
        value: unknown;
        createdAt: string;
        updatedAt: string;
    };
};

export type DeleteSystemConfigsByKeyResponse = DeleteSystemConfigsByKeyResponses[keyof DeleteSystemConfigsByKeyResponses];

export type GetSystemConfigsByKeyData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/system-configs/{key}';
};

export type GetSystemConfigsByKeyErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetSystemConfigsByKeyError = GetSystemConfigsByKeyErrors[keyof GetSystemConfigsByKeyErrors];

export type GetSystemConfigsByKeyResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        key: string;
        value: unknown;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetSystemConfigsByKeyResponse = GetSystemConfigsByKeyResponses[keyof GetSystemConfigsByKeyResponses];

export type PutSystemConfigsByKeyData = {
    body: {
        value: unknown;
    };
    path: {
        key: string;
    };
    query?: never;
    url: '/system-configs/{key}';
};

export type PutSystemConfigsByKeyErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PutSystemConfigsByKeyError = PutSystemConfigsByKeyErrors[keyof PutSystemConfigsByKeyErrors];

export type PutSystemConfigsByKeyResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        key: string;
        value: unknown;
        createdAt: string;
        updatedAt: string;
    };
};

export type PutSystemConfigsByKeyResponse = PutSystemConfigsByKeyResponses[keyof PutSystemConfigsByKeyResponses];

export type GetAgentSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agent/settings/';
};

export type GetAgentSettingsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type GetAgentSettingsError = GetAgentSettingsErrors[keyof GetAgentSettingsErrors];

export type GetAgentSettingsResponses = {
    /**
     * Response for status 200
     */
    200: {
        systemPrompt?: string;
        promptProfile?: 'coding' | 'free';
        appendSystemPrompt?: string;
        thinkingLevel?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
        compaction?: {
            enabled?: boolean;
            reserveTokens?: number;
            keepRecentTokens?: number;
            autoCompactTokenLimit?: number;
        };
    };
};

export type GetAgentSettingsResponse = GetAgentSettingsResponses[keyof GetAgentSettingsResponses];

export type PutAgentSettingsData = {
    body: {
        systemPrompt?: string;
        promptProfile?: 'coding' | 'free';
        appendSystemPrompt?: string;
        thinkingLevel?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
        compaction?: {
            enabled?: boolean;
            reserveTokens?: number;
            keepRecentTokens?: number;
            autoCompactTokenLimit?: number;
        };
    };
    path?: never;
    query?: never;
    url: '/agent/settings/';
};

export type PutAgentSettingsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PutAgentSettingsError = PutAgentSettingsErrors[keyof PutAgentSettingsErrors];

export type PutAgentSettingsResponses = {
    /**
     * Response for status 200
     */
    200: {
        systemPrompt?: string;
        promptProfile?: 'coding' | 'free';
        appendSystemPrompt?: string;
        thinkingLevel?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
        compaction?: {
            enabled?: boolean;
            reserveTokens?: number;
            keepRecentTokens?: number;
            autoCompactTokenLimit?: number;
        };
    };
};

export type PutAgentSettingsResponse = PutAgentSettingsResponses[keyof PutAgentSettingsResponses];

export type GetAgentProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agent/providers/';
};

export type GetAgentProvidersErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
};

export type GetAgentProvidersError = GetAgentProvidersErrors[keyof GetAgentProvidersErrors];

export type GetAgentProvidersResponses = {
    /**
     * Response for status 200
     */
    200: {
        activeProviderId?: string;
        providers: Array<{
            id: string;
            provider: string;
            model: string;
            baseUrl?: string;
            headers?: {
                [key: string]: string;
            };
            apiKeyPreview?: string;
            hasApiKey: boolean;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetAgentProvidersResponse = GetAgentProvidersResponses[keyof GetAgentProvidersResponses];

export type PostAgentProvidersData = {
    body: {
        provider: string;
        model: string;
        apiKey?: string;
        baseUrl?: string;
        headers?: {
            [key: string]: string;
        };
        activate?: boolean;
    };
    path?: never;
    query?: never;
    url: '/agent/providers/';
};

export type PostAgentProvidersErrors = {
    /**
     * Response for status 400
     */
    400: {
        error: string;
    };
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
};

export type PostAgentProvidersError = PostAgentProvidersErrors[keyof PostAgentProvidersErrors];

export type PostAgentProvidersResponses = {
    /**
     * Response for status 201
     */
    201: {
        activeProviderId?: string;
        providers: Array<{
            id: string;
            provider: string;
            model: string;
            baseUrl?: string;
            headers?: {
                [key: string]: string;
            };
            apiKeyPreview?: string;
            hasApiKey: boolean;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type PostAgentProvidersResponse = PostAgentProvidersResponses[keyof PostAgentProvidersResponses];

export type DeleteAgentProvidersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/providers/{id}';
};

export type DeleteAgentProvidersByIdErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 409
     */
    409: {
        error: string;
    };
};

export type DeleteAgentProvidersByIdError = DeleteAgentProvidersByIdErrors[keyof DeleteAgentProvidersByIdErrors];

export type DeleteAgentProvidersByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        provider: string;
        model: string;
        baseUrl?: string;
        headers?: {
            [key: string]: string;
        };
        apiKeyPreview?: string;
        hasApiKey: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type DeleteAgentProvidersByIdResponse = DeleteAgentProvidersByIdResponses[keyof DeleteAgentProvidersByIdResponses];

export type PutAgentProvidersByIdData = {
    body: {
        provider?: string;
        model?: string;
        apiKey?: string;
        baseUrl?: string | unknown;
        headers?: {
            [key: string]: string;
        } | unknown;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/providers/{id}';
};

export type PutAgentProvidersByIdErrors = {
    /**
     * Response for status 400
     */
    400: {
        error: string;
    };
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type PutAgentProvidersByIdError = PutAgentProvidersByIdErrors[keyof PutAgentProvidersByIdErrors];

export type PutAgentProvidersByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        provider: string;
        model: string;
        baseUrl?: string;
        headers?: {
            [key: string]: string;
        };
        apiKeyPreview?: string;
        hasApiKey: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type PutAgentProvidersByIdResponse = PutAgentProvidersByIdResponses[keyof PutAgentProvidersByIdResponses];

export type PostAgentProvidersByIdActivateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/providers/{id}/activate';
};

export type PostAgentProvidersByIdActivateErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type PostAgentProvidersByIdActivateError = PostAgentProvidersByIdActivateErrors[keyof PostAgentProvidersByIdActivateErrors];

export type PostAgentProvidersByIdActivateResponses = {
    /**
     * Response for status 200
     */
    200: {
        activeProviderId?: string;
        providers: Array<{
            id: string;
            provider: string;
            model: string;
            baseUrl?: string;
            headers?: {
                [key: string]: string;
            };
            apiKeyPreview?: string;
            hasApiKey: boolean;
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type PostAgentProvidersByIdActivateResponse = PostAgentProvidersByIdActivateResponses[keyof PostAgentProvidersByIdActivateResponses];

export type GetWorkspacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workspaces/';
};

export type GetWorkspacesErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
};

export type GetWorkspacesError = GetWorkspacesErrors[keyof GetWorkspacesErrors];

export type GetWorkspacesResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetWorkspacesResponse = GetWorkspacesResponses[keyof GetWorkspacesResponses];

export type PostWorkspacesData = {
    body: {
        name: string;
        rootPath?: string;
        telegramChatId?: string;
        telegramUserId?: string;
        forkedFromSessionId?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/workspaces/';
};

export type PostWorkspacesErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostWorkspacesError = PostWorkspacesErrors[keyof PostWorkspacesErrors];

export type PostWorkspacesResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostWorkspacesResponse = PostWorkspacesResponses[keyof PostWorkspacesResponses];

export type GetWorkspacesSearchData = {
    body?: never;
    path?: never;
    query: {
        chatId: string;
        userId?: string;
        query?: string;
        status?: 'active' | 'archived';
        limit?: number;
        offset?: number;
    };
    url: '/workspaces/search';
};

export type GetWorkspacesSearchErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
};

export type GetWorkspacesSearchError = GetWorkspacesSearchErrors[keyof GetWorkspacesSearchErrors];

export type GetWorkspacesSearchResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetWorkspacesSearchResponse = GetWorkspacesSearchResponses[keyof GetWorkspacesSearchResponses];

export type GetWorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}';
};

export type GetWorkspacesByIdErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetWorkspacesByIdError = GetWorkspacesByIdErrors[keyof GetWorkspacesByIdErrors];

export type GetWorkspacesByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetWorkspacesByIdResponse = GetWorkspacesByIdResponses[keyof GetWorkspacesByIdResponses];

export type GetWorkspacesByIdSettingsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}/settings';
};

export type GetWorkspacesByIdSettingsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type GetWorkspacesByIdSettingsError = GetWorkspacesByIdSettingsErrors[keyof GetWorkspacesByIdSettingsErrors];

export type GetWorkspacesByIdSettingsResponses = {
    /**
     * Response for status 200
     */
    200: {
        sessionId: string;
        sessionSettings: {
            systemPrompt?: string;
            promptProfile?: 'coding' | 'free';
            appendSystemPrompt?: string;
            thinkingLevel?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
            compaction?: {
                enabled?: boolean;
                reserveTokens?: number;
                keepRecentTokens?: number;
                autoCompactTokenLimit?: number;
            };
        };
        globalSettings: {
            systemPrompt?: string;
            promptProfile?: 'coding' | 'free';
            appendSystemPrompt?: string;
            thinkingLevel?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
            compaction?: {
                enabled?: boolean;
                reserveTokens?: number;
                keepRecentTokens?: number;
                autoCompactTokenLimit?: number;
            };
        };
        effectiveSettings: {
            systemPrompt?: string;
            promptProfile?: 'coding' | 'free';
            appendSystemPrompt?: string;
            thinkingLevel?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
            compaction?: {
                enabled?: boolean;
                reserveTokens?: number;
                keepRecentTokens?: number;
                autoCompactTokenLimit?: number;
            };
        };
        updatedAt?: string;
    };
};

export type GetWorkspacesByIdSettingsResponse = GetWorkspacesByIdSettingsResponses[keyof GetWorkspacesByIdSettingsResponses];

export type PatchWorkspacesByIdSettingsData = {
    body: {
        systemPrompt?: string;
        promptProfile?: 'coding' | 'free';
        appendSystemPrompt?: string;
        thinkingLevel?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
        compaction?: {
            enabled?: boolean;
            reserveTokens?: number;
            keepRecentTokens?: number;
            autoCompactTokenLimit?: number;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}/settings';
};

export type PatchWorkspacesByIdSettingsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PatchWorkspacesByIdSettingsError = PatchWorkspacesByIdSettingsErrors[keyof PatchWorkspacesByIdSettingsErrors];

export type PatchWorkspacesByIdSettingsResponses = {
    /**
     * Response for status 200
     */
    200: {
        sessionId: string;
        sessionSettings: {
            systemPrompt?: string;
            promptProfile?: 'coding' | 'free';
            appendSystemPrompt?: string;
            thinkingLevel?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
            compaction?: {
                enabled?: boolean;
                reserveTokens?: number;
                keepRecentTokens?: number;
                autoCompactTokenLimit?: number;
            };
        };
        globalSettings: {
            systemPrompt?: string;
            promptProfile?: 'coding' | 'free';
            appendSystemPrompt?: string;
            thinkingLevel?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
            compaction?: {
                enabled?: boolean;
                reserveTokens?: number;
                keepRecentTokens?: number;
                autoCompactTokenLimit?: number;
            };
        };
        effectiveSettings: {
            systemPrompt?: string;
            promptProfile?: 'coding' | 'free';
            appendSystemPrompt?: string;
            thinkingLevel?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
            compaction?: {
                enabled?: boolean;
                reserveTokens?: number;
                keepRecentTokens?: number;
                autoCompactTokenLimit?: number;
            };
        };
        updatedAt?: string;
    };
};

export type PatchWorkspacesByIdSettingsResponse = PatchWorkspacesByIdSettingsResponses[keyof PatchWorkspacesByIdSettingsResponses];

export type GetWorkspacesByIdUsageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}/usage';
};

export type GetWorkspacesByIdUsageErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type GetWorkspacesByIdUsageError = GetWorkspacesByIdUsageErrors[keyof GetWorkspacesByIdUsageErrors];

export type GetWorkspacesByIdUsageResponses = {
    /**
     * Response for status 200
     */
    200: {
        sessionId: string;
        model?: {
            provider: string;
            model: string;
            contextWindow?: number;
        };
        context: {
            estimatedTokens: number;
            window?: number;
            breakdown?: {
                systemPromptTokens: number;
                messageTokens: number;
                totalTokens: number;
                reserveTokens: number;
                freeTokens: number;
                systemPrompt: {
                    basePromptTokens: number;
                    toolsTokens: number;
                    guidelinesTokens: number;
                    appendPromptTokens: number;
                    contextFilesTokens: number;
                    skillsTokens: number;
                    runtimeTokens: number;
                    isCustomPrompt: boolean;
                    promptProfile?: 'coding' | 'free';
                };
                contextFiles: Array<{
                    path: string;
                    tokens: number;
                }>;
                skills: Array<{
                    name: string;
                    origin: 'package' | 'workspace' | 'user' | 'path';
                    tokens: number;
                }>;
                notes?: Array<string>;
            };
        };
        usage: {
            inputTokens: number;
            outputTokens: number;
            cacheReadTokens: number;
            cacheWriteTokens: number;
            totalTokens: number;
            cost: {
                input: number;
                output: number;
                cacheRead: number;
                cacheWrite: number;
                total: number;
            };
        };
    };
};

export type GetWorkspacesByIdUsageResponse = GetWorkspacesByIdUsageResponses[keyof GetWorkspacesByIdUsageResponses];

export type PostWorkspacesByIdArchiveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}/archive';
};

export type PostWorkspacesByIdArchiveErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostWorkspacesByIdArchiveError = PostWorkspacesByIdArchiveErrors[keyof PostWorkspacesByIdArchiveErrors];

export type PostWorkspacesByIdArchiveResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        status: 'active' | 'archived';
        rootPath?: string;
        metadata?: {
            [key: string]: unknown;
        };
        accessedAt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostWorkspacesByIdArchiveResponse = PostWorkspacesByIdArchiveResponses[keyof PostWorkspacesByIdArchiveResponses];

export type PostWorkspacesByIdRunsData = {
    body: {
        prompt: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}/runs';
};

export type PostWorkspacesByIdRunsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostWorkspacesByIdRunsError = PostWorkspacesByIdRunsErrors[keyof PostWorkspacesByIdRunsErrors];

export type PostWorkspacesByIdRunsResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        sessionId: string;
        prompt: string;
        status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
        summary?: string;
        error?: string;
        startedAt?: string;
        finishedAt?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostWorkspacesByIdRunsResponse = PostWorkspacesByIdRunsResponses[keyof PostWorkspacesByIdRunsResponses];

export type PostWorkspacesByIdCompactData = {
    body: {
        keepRecentTokens?: number;
        customInstructions?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}/compact';
};

export type PostWorkspacesByIdCompactErrors = {
    /**
     * Response for status 400
     */
    400: {
        error: string;
    };
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 409
     */
    409: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostWorkspacesByIdCompactError = PostWorkspacesByIdCompactErrors[keyof PostWorkspacesByIdCompactErrors];

export type PostWorkspacesByIdCompactResponses = {
    /**
     * Response for status 200
     */
    200: {
        sessionId: string;
        summary: string;
        didCompact: boolean;
    };
};

export type PostWorkspacesByIdCompactResponse = PostWorkspacesByIdCompactResponses[keyof PostWorkspacesByIdCompactResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetRunsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}';
};

export type GetRunsByIdErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdError = GetRunsByIdErrors[keyof GetRunsByIdErrors];

export type GetRunsByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        sessionId: string;
        prompt: string;
        status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
        summary?: string;
        error?: string;
        startedAt?: string;
        finishedAt?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetRunsByIdResponse = GetRunsByIdResponses[keyof GetRunsByIdResponses];

export type GetRunsByIdEventsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/events';
};

export type GetRunsByIdEventsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdEventsError = GetRunsByIdEventsErrors[keyof GetRunsByIdEventsErrors];

export type GetRunsByIdEventsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        runId: string;
        type: 'run.queued' | 'run.started' | 'run.progress' | 'run.completed' | 'run.failed' | 'run.canceled' | 'tool.executed';
        message: string;
        payload?: {
            [key: string]: unknown;
        };
        timestamp: string;
    }>;
};

export type GetRunsByIdEventsResponse = GetRunsByIdEventsResponses[keyof GetRunsByIdEventsResponses];

export type PostRunsByIdEventsData = {
    body: {
        type: 'run.queued' | 'run.started' | 'run.progress' | 'run.completed' | 'run.failed' | 'run.canceled' | 'tool.executed';
        message: string;
        payload?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/events';
};

export type PostRunsByIdEventsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostRunsByIdEventsError = PostRunsByIdEventsErrors[keyof PostRunsByIdEventsErrors];

export type PostRunsByIdEventsResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        runId: string;
        type: 'run.queued' | 'run.started' | 'run.progress' | 'run.completed' | 'run.failed' | 'run.canceled' | 'tool.executed';
        message: string;
        payload?: {
            [key: string]: unknown;
        };
        timestamp: string;
    };
};

export type PostRunsByIdEventsResponse = PostRunsByIdEventsResponses[keyof PostRunsByIdEventsResponses];

export type GetRunsByIdToolExecutionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/tool-executions';
};

export type GetRunsByIdToolExecutionsErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdToolExecutionsError = GetRunsByIdToolExecutionsErrors[keyof GetRunsByIdToolExecutionsErrors];

export type GetRunsByIdToolExecutionsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        runId: string;
        tool: string;
        input: unknown;
        output: unknown;
        status: 'succeeded' | 'failed';
        error?: string;
        startedAt: string;
        endedAt?: string;
    }>;
};

export type GetRunsByIdToolExecutionsResponse = GetRunsByIdToolExecutionsResponses[keyof GetRunsByIdToolExecutionsResponses];

export type PostRunsByIdCancelData = {
    body: {
        reason?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/cancel';
};

export type PostRunsByIdCancelErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: string;
    };
};

export type PostRunsByIdCancelError = PostRunsByIdCancelErrors[keyof PostRunsByIdCancelErrors];

export type PostRunsByIdCancelResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        sessionId: string;
        prompt: string;
        status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
        summary?: string;
        error?: string;
        startedAt?: string;
        finishedAt?: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostRunsByIdCancelResponse = PostRunsByIdCancelResponses[keyof PostRunsByIdCancelResponses];

export type GetRunsByIdStreamData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}/stream';
};

export type GetRunsByIdStreamErrors = {
    /**
     * Response for status 401
     */
    401: {
        error: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: string;
    };
};

export type GetRunsByIdStreamError = GetRunsByIdStreamErrors[keyof GetRunsByIdStreamErrors];

export type GetRunsByIdStreamResponses = {
    /**
     * text/event-stream
     */
    200: unknown;
};
