// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zGetWorkspacesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostWorkspacesData = z.object({
    body: z.object({
        name: z.string().min(1),
        rootPath: z.optional(z.string()),
        telegramChatId: z.optional(z.string()),
        telegramUserId: z.optional(z.string()),
        forkedFromSessionId: z.optional(z.string()),
        metadata: z.optional(z.record(z.string(), z.unknown()))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetWorkspacesSearchData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        chatId: z.string().min(1),
        userId: z.optional(z.string()),
        query: z.optional(z.string())
    })
});

export const zGetWorkspacesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPostWorkspacesByIdRunsData = z.object({
    body: z.object({
        prompt: z.string().min(1)
    }),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetHealthData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetRunsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdEventsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPostRunsByIdEventsData = z.object({
    body: z.object({
        type: z.enum([
            'run.queued',
            'run.started',
            'run.progress',
            'run.completed',
            'run.failed',
            'run.canceled',
            'tool.executed'
        ]),
        message: z.string().min(1),
        payload: z.optional(z.record(z.string(), z.unknown()))
    }),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdToolExecutionsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPostRunsByIdCancelData = z.object({
    body: z.object({
        reason: z.optional(z.string())
    }),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdStreamData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});
