// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zGetSystemConfigsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zDeleteSystemConfigsByKeyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        key: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetSystemConfigsByKeyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        key: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPutSystemConfigsByKeyData = z.object({
    body: z.object({
        value: z.unknown()
    }),
    path: z.object({
        key: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetAgentSettingsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPutAgentSettingsData = z.object({
    body: z.object({
        systemPrompt: z.optional(z.string()),
        promptProfile: z.optional(z.enum(['coding', 'free'])),
        appendSystemPrompt: z.optional(z.string()),
        thinkingLevel: z.optional(z.enum([
            'off',
            'minimal',
            'low',
            'medium',
            'high',
            'xhigh'
        ])),
        compaction: z.optional(z.object({
            enabled: z.optional(z.boolean()),
            reserveTokens: z.optional(z.int().lte(9007199254740991)),
            keepRecentTokens: z.optional(z.int().lte(9007199254740991))
        }))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetAgentProvidersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostAgentProvidersData = z.object({
    body: z.object({
        provider: z.string().min(1),
        model: z.string().min(1),
        apiKey: z.optional(z.string().min(1)),
        baseUrl: z.optional(z.url()),
        headers: z.optional(z.record(z.string(), z.string())),
        activate: z.optional(z.boolean())
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zDeleteAgentProvidersByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPutAgentProvidersByIdData = z.object({
    body: z.object({
        provider: z.optional(z.string().min(1)),
        model: z.optional(z.string().min(1)),
        apiKey: z.optional(z.string().min(1)),
        baseUrl: z.optional(z.union([
            z.url(),
            z.unknown()
        ])),
        headers: z.optional(z.union([
            z.record(z.string(), z.string()),
            z.unknown()
        ]))
    }),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPostAgentProvidersByIdActivateData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetWorkspacesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostWorkspacesData = z.object({
    body: z.object({
        name: z.string().min(1),
        rootPath: z.optional(z.string()),
        telegramChatId: z.optional(z.string()),
        telegramUserId: z.optional(z.string()),
        forkedFromSessionId: z.optional(z.string()),
        metadata: z.optional(z.record(z.string(), z.unknown()))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetWorkspacesSearchData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        chatId: z.string().min(1),
        userId: z.optional(z.string()),
        query: z.optional(z.string()),
        status: z.optional(z.enum(['active', 'archived'])),
        limit: z.optional(z.int().gte(1).lte(50)),
        offset: z.optional(z.int().gte(0).lte(9007199254740991))
    })
});

export const zGetWorkspacesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetWorkspacesByIdSettingsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPatchWorkspacesByIdSettingsData = z.object({
    body: z.object({
        systemPrompt: z.optional(z.string()),
        promptProfile: z.optional(z.enum(['coding', 'free'])),
        appendSystemPrompt: z.optional(z.string()),
        thinkingLevel: z.optional(z.enum([
            'off',
            'minimal',
            'low',
            'medium',
            'high',
            'xhigh'
        ])),
        compaction: z.optional(z.object({
            enabled: z.optional(z.boolean()),
            reserveTokens: z.optional(z.int().lte(9007199254740991)),
            keepRecentTokens: z.optional(z.int().lte(9007199254740991))
        }))
    }),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetWorkspacesByIdUsageData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPostWorkspacesByIdArchiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPostWorkspacesByIdRunsData = z.object({
    body: z.object({
        prompt: z.string().min(1)
    }),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPostWorkspacesByIdCompactData = z.object({
    body: z.object({
        keepRecentTokens: z.optional(z.int().gte(0).lte(9007199254740991)),
        customInstructions: z.optional(z.string().min(1))
    }),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetHealthData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetRunsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdEventsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPostRunsByIdEventsData = z.object({
    body: z.object({
        type: z.enum([
            'run.queued',
            'run.started',
            'run.progress',
            'run.completed',
            'run.failed',
            'run.canceled',
            'tool.executed'
        ]),
        message: z.string().min(1),
        payload: z.optional(z.record(z.string(), z.unknown()))
    }),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdToolExecutionsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPostRunsByIdCancelData = z.object({
    body: z.object({
        reason: z.optional(z.string())
    }),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdStreamData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});
