// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zGetHealthData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetWorkspacesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostWorkspacesData = z.object({
    body: z.object({
        name: z.string().min(1),
        rootPath: z.optional(z.string()),
        metadata: z.optional(z.record(z.string(), z.unknown()))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetWorkspacesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zPostWorkspacesByIdRunsData = z.object({
    body: z.object({
        prompt: z.string().min(1)
    }),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdEventsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdToolExecutionsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdMessagesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});

export const zGetRunsByIdStreamData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().min(1)
    }),
    query: z.optional(z.never())
});
