services:
  postgres:
    image: postgres:latest
    container_name: bbot-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bbot
      POSTGRES_USER: bbot
      POSTGRES_PASSWORD: bbot
    volumes:
      - bbot_postgres:/var/lib/postgresql/data

volumes:
  bbot_postgres:
