// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteSystemConfigsByKey, getHealth, getRunsById, getRunsByIdEvents, getRunsByIdStream, getRunsByIdToolExecutions, getSystemConfigs, getSystemConfigsByKey, getWorkspaces, getWorkspacesById, getWorkspacesSearch, type Options, postRunsByIdCancel, postRunsByIdEvents, postWorkspaces, postWorkspacesByIdArchive, postWorkspacesByIdCompact, postWorkspacesByIdRuns, putSystemConfigsByKey } from '../sdk.gen';
import type { DeleteSystemConfigsByKeyData, DeleteSystemConfigsByKeyError, DeleteSystemConfigsByKeyResponse, GetHealthData, GetRunsByIdData, GetRunsByIdError, GetRunsByIdEventsData, GetRunsByIdEventsError, GetRunsByIdEventsResponse, GetRunsByIdResponse, GetRunsByIdStreamData, GetRunsByIdStreamError, GetRunsByIdToolExecutionsData, GetRunsByIdToolExecutionsError, GetRunsByIdToolExecutionsResponse, GetSystemConfigsByKeyData, GetSystemConfigsByKeyError, GetSystemConfigsByKeyResponse, GetSystemConfigsData, GetSystemConfigsError, GetSystemConfigsResponse, GetWorkspacesByIdData, GetWorkspacesByIdError, GetWorkspacesByIdResponse, GetWorkspacesData, GetWorkspacesError, GetWorkspacesResponse, GetWorkspacesSearchData, GetWorkspacesSearchError, GetWorkspacesSearchResponse, PostRunsByIdCancelData, PostRunsByIdCancelError, PostRunsByIdCancelResponse, PostRunsByIdEventsData, PostRunsByIdEventsError, PostRunsByIdEventsResponse, PostWorkspacesByIdArchiveData, PostWorkspacesByIdArchiveError, PostWorkspacesByIdArchiveResponse, PostWorkspacesByIdCompactData, PostWorkspacesByIdCompactError, PostWorkspacesByIdCompactResponse, PostWorkspacesByIdRunsData, PostWorkspacesByIdRunsError, PostWorkspacesByIdRunsResponse, PostWorkspacesData, PostWorkspacesError, PostWorkspacesResponse, PutSystemConfigsByKeyData, PutSystemConfigsByKeyError, PutSystemConfigsByKeyResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getSystemConfigsQueryKey = (options?: Options<GetSystemConfigsData>) => createQueryKey('getSystemConfigs', options);

export const getSystemConfigsOptions = (options?: Options<GetSystemConfigsData>) => queryOptions<GetSystemConfigsResponse, GetSystemConfigsError, GetSystemConfigsResponse, ReturnType<typeof getSystemConfigsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSystemConfigs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSystemConfigsQueryKey(options)
});

export const deleteSystemConfigsByKeyMutation = (options?: Partial<Options<DeleteSystemConfigsByKeyData>>): UseMutationOptions<DeleteSystemConfigsByKeyResponse, DeleteSystemConfigsByKeyError, Options<DeleteSystemConfigsByKeyData>> => {
    const mutationOptions: UseMutationOptions<DeleteSystemConfigsByKeyResponse, DeleteSystemConfigsByKeyError, Options<DeleteSystemConfigsByKeyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteSystemConfigsByKey({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSystemConfigsByKeyQueryKey = (options: Options<GetSystemConfigsByKeyData>) => createQueryKey('getSystemConfigsByKey', options);

export const getSystemConfigsByKeyOptions = (options: Options<GetSystemConfigsByKeyData>) => queryOptions<GetSystemConfigsByKeyResponse, GetSystemConfigsByKeyError, GetSystemConfigsByKeyResponse, ReturnType<typeof getSystemConfigsByKeyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSystemConfigsByKey({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSystemConfigsByKeyQueryKey(options)
});

export const putSystemConfigsByKeyMutation = (options?: Partial<Options<PutSystemConfigsByKeyData>>): UseMutationOptions<PutSystemConfigsByKeyResponse, PutSystemConfigsByKeyError, Options<PutSystemConfigsByKeyData>> => {
    const mutationOptions: UseMutationOptions<PutSystemConfigsByKeyResponse, PutSystemConfigsByKeyError, Options<PutSystemConfigsByKeyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putSystemConfigsByKey({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWorkspacesQueryKey = (options?: Options<GetWorkspacesData>) => createQueryKey('getWorkspaces', options);

export const getWorkspacesOptions = (options?: Options<GetWorkspacesData>) => queryOptions<GetWorkspacesResponse, GetWorkspacesError, GetWorkspacesResponse, ReturnType<typeof getWorkspacesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkspaces({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkspacesQueryKey(options)
});

export const postWorkspacesMutation = (options?: Partial<Options<PostWorkspacesData>>): UseMutationOptions<PostWorkspacesResponse, PostWorkspacesError, Options<PostWorkspacesData>> => {
    const mutationOptions: UseMutationOptions<PostWorkspacesResponse, PostWorkspacesError, Options<PostWorkspacesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWorkspaces({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWorkspacesSearchQueryKey = (options: Options<GetWorkspacesSearchData>) => createQueryKey('getWorkspacesSearch', options);

export const getWorkspacesSearchOptions = (options: Options<GetWorkspacesSearchData>) => queryOptions<GetWorkspacesSearchResponse, GetWorkspacesSearchError, GetWorkspacesSearchResponse, ReturnType<typeof getWorkspacesSearchQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkspacesSearch({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkspacesSearchQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getWorkspacesSearchInfiniteQueryKey = (options: Options<GetWorkspacesSearchData>): QueryKey<Options<GetWorkspacesSearchData>> => createQueryKey('getWorkspacesSearch', options, true);

export const getWorkspacesSearchInfiniteOptions = (options: Options<GetWorkspacesSearchData>) => infiniteQueryOptions<GetWorkspacesSearchResponse, GetWorkspacesSearchError, InfiniteData<GetWorkspacesSearchResponse>, QueryKey<Options<GetWorkspacesSearchData>>, number | Pick<QueryKey<Options<GetWorkspacesSearchData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetWorkspacesSearchData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getWorkspacesSearch({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkspacesSearchInfiniteQueryKey(options)
});

export const getWorkspacesByIdQueryKey = (options: Options<GetWorkspacesByIdData>) => createQueryKey('getWorkspacesById', options);

export const getWorkspacesByIdOptions = (options: Options<GetWorkspacesByIdData>) => queryOptions<GetWorkspacesByIdResponse, GetWorkspacesByIdError, GetWorkspacesByIdResponse, ReturnType<typeof getWorkspacesByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkspacesById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkspacesByIdQueryKey(options)
});

export const postWorkspacesByIdArchiveMutation = (options?: Partial<Options<PostWorkspacesByIdArchiveData>>): UseMutationOptions<PostWorkspacesByIdArchiveResponse, PostWorkspacesByIdArchiveError, Options<PostWorkspacesByIdArchiveData>> => {
    const mutationOptions: UseMutationOptions<PostWorkspacesByIdArchiveResponse, PostWorkspacesByIdArchiveError, Options<PostWorkspacesByIdArchiveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWorkspacesByIdArchive({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postWorkspacesByIdRunsMutation = (options?: Partial<Options<PostWorkspacesByIdRunsData>>): UseMutationOptions<PostWorkspacesByIdRunsResponse, PostWorkspacesByIdRunsError, Options<PostWorkspacesByIdRunsData>> => {
    const mutationOptions: UseMutationOptions<PostWorkspacesByIdRunsResponse, PostWorkspacesByIdRunsError, Options<PostWorkspacesByIdRunsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWorkspacesByIdRuns({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postWorkspacesByIdCompactMutation = (options?: Partial<Options<PostWorkspacesByIdCompactData>>): UseMutationOptions<PostWorkspacesByIdCompactResponse, PostWorkspacesByIdCompactError, Options<PostWorkspacesByIdCompactData>> => {
    const mutationOptions: UseMutationOptions<PostWorkspacesByIdCompactResponse, PostWorkspacesByIdCompactError, Options<PostWorkspacesByIdCompactData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWorkspacesByIdCompact({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const getRunsByIdQueryKey = (options: Options<GetRunsByIdData>) => createQueryKey('getRunsById', options);

export const getRunsByIdOptions = (options: Options<GetRunsByIdData>) => queryOptions<GetRunsByIdResponse, GetRunsByIdError, GetRunsByIdResponse, ReturnType<typeof getRunsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRunsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunsByIdQueryKey(options)
});

export const getRunsByIdEventsQueryKey = (options: Options<GetRunsByIdEventsData>) => createQueryKey('getRunsByIdEvents', options);

export const getRunsByIdEventsOptions = (options: Options<GetRunsByIdEventsData>) => queryOptions<GetRunsByIdEventsResponse, GetRunsByIdEventsError, GetRunsByIdEventsResponse, ReturnType<typeof getRunsByIdEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRunsByIdEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunsByIdEventsQueryKey(options)
});

export const postRunsByIdEventsMutation = (options?: Partial<Options<PostRunsByIdEventsData>>): UseMutationOptions<PostRunsByIdEventsResponse, PostRunsByIdEventsError, Options<PostRunsByIdEventsData>> => {
    const mutationOptions: UseMutationOptions<PostRunsByIdEventsResponse, PostRunsByIdEventsError, Options<PostRunsByIdEventsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postRunsByIdEvents({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRunsByIdToolExecutionsQueryKey = (options: Options<GetRunsByIdToolExecutionsData>) => createQueryKey('getRunsByIdToolExecutions', options);

export const getRunsByIdToolExecutionsOptions = (options: Options<GetRunsByIdToolExecutionsData>) => queryOptions<GetRunsByIdToolExecutionsResponse, GetRunsByIdToolExecutionsError, GetRunsByIdToolExecutionsResponse, ReturnType<typeof getRunsByIdToolExecutionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRunsByIdToolExecutions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunsByIdToolExecutionsQueryKey(options)
});

export const postRunsByIdCancelMutation = (options?: Partial<Options<PostRunsByIdCancelData>>): UseMutationOptions<PostRunsByIdCancelResponse, PostRunsByIdCancelError, Options<PostRunsByIdCancelData>> => {
    const mutationOptions: UseMutationOptions<PostRunsByIdCancelResponse, PostRunsByIdCancelError, Options<PostRunsByIdCancelData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postRunsByIdCancel({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRunsByIdStreamQueryKey = (options: Options<GetRunsByIdStreamData>) => createQueryKey('getRunsByIdStream', options);

export const getRunsByIdStreamOptions = (options: Options<GetRunsByIdStreamData>) => queryOptions<unknown, GetRunsByIdStreamError, unknown, ReturnType<typeof getRunsByIdStreamQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRunsByIdStream({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunsByIdStreamQueryKey(options)
});
