// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getHealth, getRunsById, getRunsByIdEvents, getRunsByIdMessages, getRunsByIdStream, getRunsByIdToolExecutions, getWorkspaces, getWorkspacesById, type Options, postRunsByIdEvents, postWorkspaces, postWorkspacesByIdRuns } from '../sdk.gen';
import type { GetHealthData, GetRunsByIdData, GetRunsByIdError, GetRunsByIdEventsData, GetRunsByIdEventsError, GetRunsByIdEventsResponse, GetRunsByIdMessagesData, GetRunsByIdMessagesError, GetRunsByIdMessagesResponse, GetRunsByIdResponse, GetRunsByIdStreamData, GetRunsByIdStreamError, GetRunsByIdToolExecutionsData, GetRunsByIdToolExecutionsError, GetRunsByIdToolExecutionsResponse, GetWorkspacesByIdData, GetWorkspacesByIdError, GetWorkspacesByIdResponse, GetWorkspacesData, GetWorkspacesError, GetWorkspacesResponse, PostRunsByIdEventsData, PostRunsByIdEventsError, PostRunsByIdEventsResponse, PostWorkspacesByIdRunsData, PostWorkspacesByIdRunsError, PostWorkspacesByIdRunsResponse, PostWorkspacesData, PostWorkspacesError, PostWorkspacesResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const getWorkspacesQueryKey = (options?: Options<GetWorkspacesData>) => createQueryKey('getWorkspaces', options);

export const getWorkspacesOptions = (options?: Options<GetWorkspacesData>) => queryOptions<GetWorkspacesResponse, GetWorkspacesError, GetWorkspacesResponse, ReturnType<typeof getWorkspacesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkspaces({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkspacesQueryKey(options)
});

export const postWorkspacesMutation = (options?: Partial<Options<PostWorkspacesData>>): UseMutationOptions<PostWorkspacesResponse, PostWorkspacesError, Options<PostWorkspacesData>> => {
    const mutationOptions: UseMutationOptions<PostWorkspacesResponse, PostWorkspacesError, Options<PostWorkspacesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWorkspaces({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWorkspacesByIdQueryKey = (options: Options<GetWorkspacesByIdData>) => createQueryKey('getWorkspacesById', options);

export const getWorkspacesByIdOptions = (options: Options<GetWorkspacesByIdData>) => queryOptions<GetWorkspacesByIdResponse, GetWorkspacesByIdError, GetWorkspacesByIdResponse, ReturnType<typeof getWorkspacesByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWorkspacesById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWorkspacesByIdQueryKey(options)
});

export const postWorkspacesByIdRunsMutation = (options?: Partial<Options<PostWorkspacesByIdRunsData>>): UseMutationOptions<PostWorkspacesByIdRunsResponse, PostWorkspacesByIdRunsError, Options<PostWorkspacesByIdRunsData>> => {
    const mutationOptions: UseMutationOptions<PostWorkspacesByIdRunsResponse, PostWorkspacesByIdRunsError, Options<PostWorkspacesByIdRunsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWorkspacesByIdRuns({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRunsByIdQueryKey = (options: Options<GetRunsByIdData>) => createQueryKey('getRunsById', options);

export const getRunsByIdOptions = (options: Options<GetRunsByIdData>) => queryOptions<GetRunsByIdResponse, GetRunsByIdError, GetRunsByIdResponse, ReturnType<typeof getRunsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRunsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunsByIdQueryKey(options)
});

export const getRunsByIdEventsQueryKey = (options: Options<GetRunsByIdEventsData>) => createQueryKey('getRunsByIdEvents', options);

export const getRunsByIdEventsOptions = (options: Options<GetRunsByIdEventsData>) => queryOptions<GetRunsByIdEventsResponse, GetRunsByIdEventsError, GetRunsByIdEventsResponse, ReturnType<typeof getRunsByIdEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRunsByIdEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunsByIdEventsQueryKey(options)
});

export const postRunsByIdEventsMutation = (options?: Partial<Options<PostRunsByIdEventsData>>): UseMutationOptions<PostRunsByIdEventsResponse, PostRunsByIdEventsError, Options<PostRunsByIdEventsData>> => {
    const mutationOptions: UseMutationOptions<PostRunsByIdEventsResponse, PostRunsByIdEventsError, Options<PostRunsByIdEventsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postRunsByIdEvents({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRunsByIdToolExecutionsQueryKey = (options: Options<GetRunsByIdToolExecutionsData>) => createQueryKey('getRunsByIdToolExecutions', options);

export const getRunsByIdToolExecutionsOptions = (options: Options<GetRunsByIdToolExecutionsData>) => queryOptions<GetRunsByIdToolExecutionsResponse, GetRunsByIdToolExecutionsError, GetRunsByIdToolExecutionsResponse, ReturnType<typeof getRunsByIdToolExecutionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRunsByIdToolExecutions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunsByIdToolExecutionsQueryKey(options)
});

export const getRunsByIdMessagesQueryKey = (options: Options<GetRunsByIdMessagesData>) => createQueryKey('getRunsByIdMessages', options);

export const getRunsByIdMessagesOptions = (options: Options<GetRunsByIdMessagesData>) => queryOptions<GetRunsByIdMessagesResponse, GetRunsByIdMessagesError, GetRunsByIdMessagesResponse, ReturnType<typeof getRunsByIdMessagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRunsByIdMessages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunsByIdMessagesQueryKey(options)
});

export const getRunsByIdStreamQueryKey = (options: Options<GetRunsByIdStreamData>) => createQueryKey('getRunsByIdStream', options);

export const getRunsByIdStreamOptions = (options: Options<GetRunsByIdStreamData>) => queryOptions<unknown, GetRunsByIdStreamError, unknown, ReturnType<typeof getRunsByIdStreamQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRunsByIdStream({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunsByIdStreamQueryKey(options)
});
