export const BOT_TELEGRAM_ENV = {
  BOT_TOKEN: "BOT_TOKEN",
  CORE_API_URL: "CORE_API_URL",
  CORE_API_TOKEN: "CORE_API_TOKEN",
  ALLOWED_USER_IDS: "BOT_TELEGRAM_ALLOWED_USER_IDS",
  OMNICORE_ADAPTER_ID: "OMNICORE_ADAPTER_ID",
  OMNICORE_ADAPTER_URL: "OMNICORE_ADAPTER_URL",
  OMNICORE_DATA_DIR: "OMNICORE_DATA_DIR",
  OMNICORE_ROOT: "OMNICORE_ROOT",
} as const

export const CORE_DAEMON_ENV_KEYS = [
  "CORE_API_TOKEN",
  "DATABASE_URL",
  "NODE_ENV",
  "PORT",
] as const

export const BOT_TELEGRAM_ENV_KEYS = Object.values(BOT_TELEGRAM_ENV)
