export const BOT_TELEGRAM_ENV = {
  BOT_TOKEN: "BOT_TOKEN",
  CORE_API_URL: "CORE_API_URL",
  CORE_API_TOKEN: "CORE_API_TOKEN",
  ALLOWED_USER_IDS: "BOT_TELEGRAM_ALLOWED_USER_IDS",
} as const

export const CORE_DAEMON_ENV_KEYS = [
  "CORE_API_TOKEN",
  "DATABASE_URL",
  "AGENT_PROVIDER",
  "AGENT_MODEL",
  "AGENT_BASE_URL",
  "AGENT_SYSTEM_PROMPT",
  "AGENT_PROMPT_PROFILE",
  "AGENT_APPEND_SYSTEM_PROMPT",
  "AGENT_COMPACTION_ENABLED",
  "AGENT_COMPACTION_RESERVE_TOKENS",
  "AGENT_COMPACTION_KEEP_RECENT_TOKENS",
  "AGENT_THINKING_LEVEL",
  "AGENT_MCP_SERVERS",
  "ACP_BASE_URL",
  "ACP_AGENT_NAME",
  "ACP_API_TOKEN",
  "NODE_ENV",
  "PORT",
] as const

export const BOT_TELEGRAM_ENV_KEYS = Object.values(BOT_TELEGRAM_ENV)
